### ISSUE TITLE
CUE files not correctly generated when using -singletrack function

### ISSUE THREAD

**Issue by RoberMC** [Kippykip/SBITools#1]
I was trying to convert to singletrack the game "Breath of Fire IV (USA)" from latest Redump set. It contains:

Breath of Fire IV (USA) (Track 1).bin
Breath of Fire IV (USA) (Track 2).bin
Breath of Fire IV (USA).cue

Cue file content:

> FILE "Breath of Fire IV (USA) (Track 1).bin" BINARY
>   TRACK 01 MODE2/2352
>     INDEX 01 00:00:00
> FILE "Breath of Fire IV (USA) (Track 2).bin" BINARY
>   TRACK 02 MODE2/2352
>     INDEX 01 00:00:00
> 

Drag and drop "Breath of Fire IV (USA).cue" to "singletrack.bat" generates the files:

Breath of Fire IV (USA).bin
Breath of Fire IV (USA).cue

Resulting cue file content:

> FILE "Breath of Fire IV (USA).bin" BINARY
>   TRACK 1 MODE2/2352
>     INDEX 1 00:00:00
>     INDEX 1 61:00:63
> 

The resulting Cue file format is not valid, track 2 is missing, and does not load in many programs (CDMage for example). They give error in index statement. 

The more correct format to output such a CUE file would be:

> FILE "Breath of Fire IV (USA).bin" BINARY
>   TRACK 01 MODE2/2352
>     INDEX 01 00:00:00
>   TRACK 02 MODE2/2352
>     INDEX 01 60:58:63
> 

Best regards.

**Comment by Kippykip** [comment]
oh crap, i better check that out

**Comment by Kippykip** [comment]
Alright I've found the problem. Breath of Fire IV actually uses 2 data tracks.
I wasn't aware those even existed, so when I wrote the tools I only wrote it in mind that there's ever only 1 data track and sometimes audio tracks.

I might have to do a bit of a rewrite to fix this, I'll also have to play around and see how 2 data tracks affects .CCD files too.

**Comment by Kippykip** [comment]
I have uploaded a new build of SBITools!
I did a big rewrite how CUEs/CCDs are exported when it comes to multiple data tracks. 
Breath of Fire IV now exports correctly! :smile:
